### ISSUE TITLE
Btree switch callback error

### ISSUE THREAD

**Issue by wenwei-dev** [hansonrobotics/ros-behavior-scripting#1]
When you "off" btree on webui, you get this error. 

```
[rosout][ERROR] [1458552276.485644]: bad callback: <bound method EvaControl.behavior_switch_callback of <ros_commo.EvaControl instance at 0x7fdfda610290>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
    cb(msg)
  File "ros_commo.py", line 255, in behavior_switch_callback
    self.puta.btree_stop()
  File "put_atoms.py", line 72, in btree_stop
    scheme_eval_h(self.atomspace, "(halt)")
  File "scheme_wrapper.pyx", line 47, in opencog.scheme_wrapper.scheme_eval_h (/home/wenwei/workspace/hansonrobotics/opencog/atomspace/build/opencog/cython/opencog/scheme_wrapper.cpp:1148)
RuntimeError: Backtrace:
In ice-9/boot-9.scm:
 157: 12 [catch #t #<catch-closure 279da00> ...]
In unknown file:
   ?: 11 [apply-smob/1 #<catch-closure 279da00>]
In ice-9/boot-9.scm:
 157: 10 [catch #t #<catch-closure 279d5e0> ...]
In unknown file:
   ?: 9 [apply-smob/1 #<catch-closure 279d5e0>]
   ?: 8 [call-with-input-string "(halt)" ...]
In ice-9/boot-9.scm:
2320: 7 [save-module-excursion #<procedure 2582ae0 at ice-9/eval-string.scm:65:9 ()>]
In ice-9/eval-string.scm:
  44: 6 [read-and-eval #<input: string 249b5b0> #:lang ...]
  37: 5 [lp (halt)]
In ice-9/eval.scm:
 386: 4 [eval #<memoized (halt)> ()]
 393: 3 [eval #<memoized halt> ()]
In unknown file:
   ?: 2 [memoize-variable-access! #<memoized halt> #<directory # 18fdc60>]
In ice-9/boot-9.scm:
 102: 1 [#<procedure 2580e40 at ice-9/boot-9.scm:97:6 (thrown-k . args)> unbound-variable ...]
In unknown file:
   ?: 0 [apply-smob/1 #<catch-closure 279d5a0> unbound-variable ...]

ERROR: In procedure apply-smob/1:
ERROR: Unbound variable: halt
ABORT: unbound-variable
 (/home/wenwei/workspace/hansonrobotics/opencog/atomspace/opencog/guile/SchemeEval.cc:885)
```

**Comment by wenwei-dev** [comment]
@linas It looks a bug in the HR's forked btree. I'm not sure it's solved in the original repository.
